In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn as sk
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer

%matplotlib inline

In [3]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [4]:
nltk.download("punkt") 

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [5]:
ps= PorterStemmer()
wnl = WordNetLemmatizer()

In [6]:
#TODO PREPROCESS ALL DOCUMENTS
#TODO 

In [ ]:
import chardet

with open('../dataset/RATIO.csv', mode='rb') as file:
    raw_data = file.read()
    answer = chardet.detect(raw_data)

answer

{'encoding': 'MacRoman', 'confidence': 0.597774786220692, 'language': ''}

In [34]:
dataset1  = pd.read_csv('../dataset/RATIO.csv', encoding='MacRoman')


In [33]:
dataset2  = pd.read_csv('../dataset/Equal.csv',encoding='MacRoman')


In [32]:
dataset3  = pd.read_csv('../dataset/sentiment.csv', encoding='MacRoman')


C:\Users\USER\AppData\Local\Temp\ipykernel_21808\3583425108.py:1: DtypeWarning: Columns (1,2) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset3  = pd.read_csv('../dataset/sentiment.csv', encoding='MacRoman')


In [42]:
data = pd.concat([dataset1, dataset2, dataset3], ignore_index=True)

In [43]:
data

product_name  \
0       SAMSUNG 198 L Direct Cool Single Door 5 Star R...   
1       SAMSUNG 236 L Frost Free Double Door 2 Star Re...   
2       SAMSUNG 189 L Direct Cool Single Door 5 Star R...   
3       SAMSUNG 253 L Frost Free Double Door 3 Star Co...   
4       Godrej 180 L Direct Cool Single Door 2 Star Re...   
...                                                   ...   
312297                                                NaN   
312298                                                NaN   
312299                                                NaN   
312300                                                NaN   
312301                                                NaN   

                                            product_price Rate  \
0       ?ü?ü???ü?ü?????õ?ü?ü?????ü???????ü?ü?????ü????...    1   
1       ?ü?ü???ü?ü?????õ?ü?ü?????ü???????ü?ü?????ü????...    2   
2       ?ü?ü???ü?ü?????õ?ü?ü?????ü???????ü?ü?????ü????...    3   
3       ?ü?ü???ü?ü?????õ?ü?ü?????ü???????ü?ü?????ü????...    3   
4       ?ü?ü???ü?ü?????õ?ü?ü?????ü???????ü?ü?????ü????...    3   
...                                                   ...  ...   
312297                                                NaN  5.0   
312298                                                NaN  5.0   
312299                                                NaN  2.0   
312300                                                NaN  2.0   
312301                                                NaN  NaN   

                       Review  \
0                   Very poor   
1                    Moderate   
2                        Nice   
3                   Just okay   
4              Decent product   
...                       ...   
312297              Must buy!   
312298       Perfect product!   
312299  Slightly disappointed   
312300               Moderate   
312301                    NaN   

                                                  Summary Sentiment  \
0       problems 1 it gets auto defrost randomly anyti...  positive   
1       freeze segment is tooo large so cooling segmen...  positive   
2       warranty sticker is not present when its run d...  positive   
3       everything is goodworking fine but it is silly...  positive   
4       refrigerator working fine but top and side vie...  positive   
...                                                   ...       ...   
312297         awesome product and clear sound just go it  positive   
312298                                               good  positive   
312299                         lot of echo when recording  negative   
312300  it was not that good as i expected because ya ...  negative   
312301                                                NaN       NaN   

                                              ProductName ProductPrice  
0                                                     NaN          NaN  
1                                                     NaN          NaN  
2                                                     NaN          NaN  
3                                                     NaN          NaN  
4                                                     NaN          NaN  
...                                                   ...          ...  
312297  mobspy 3.5mm Clip Microphone For Youtube | Col...        168.0  
312298  mobspy 3.5mm Clip Microphone For Youtube | Col...        168.0  
312299  mobspy 3.5mm Clip Microphone For Youtube | Col...        168.0  
312300  mobspy 3.5mm Clip Microphone For Youtube | Col...        168.0  
312301                                                            NaN  

[312302 rows x 8 columns]

In [64]:

data['agg_review'] = data['Summary'].fillna("") +" " + data['Review'].fillna("")

In [67]:
df = data[['agg_review', 'Sentiment']]
df

agg_review Sentiment
0       problems 1 it gets auto defrost randomly anyti...  positive
1       freeze segment is tooo large so cooling segmen...  positive
2       warranty sticker is not present when its run d...  positive
3       everything is goodworking fine but it is silly...  positive
4       refrigerator working fine but top and side vie...  positive
...                                                   ...       ...
312297  awesome product and clear sound just go it Mus...  positive
312298                              good Perfect product!  positive
312299   lot of echo when recording Slightly disappointed  negative
312300  it was not that good as i expected because ya ...  negative
312301                                                          NaN

[312302 rows x 2 columns]

In [ ]:
data = pd.read_csv("../dataset/Train.csv")
data

Text_ID                                Product_Description  \
0        3057  The Web Designer‰Ûªs Guide to iOS (and Android...   
1        6254  RT @mention Line for iPad 2 is longer today th...   
2        8212  Crazy that Apple is opening a temporary store ...   
3        4422  The lesson from Google One Pass: In this digit...   
4        5526  RT @mention At the panel: &quot;Your mom has a...   
...       ...                                                ...   
6359     2945  Thanks @mention for hosting this event #sxsw #...   
6360     4528  SXSW iPhone app is awesome, but iPad app crash...   
6361     6526  RT @mention RT @mention Download 20+ free trac...   
6362     2110  OH at Texas Social Media Awards: 'You don't ne...   
6363     2177  #Google launching a &quot;major&quot; new soci...   

      Product_Type  Sentiment  
0                9          2  
1                9          2  
2                9          2  
3                9          2  
4                9          2  
...            ...        ...  
6359             9          2  
6360             7          1  
6361             9          2  
6362             9          2  
6363             9          2  

[6364 rows x 4 columns]

In [ ]:
sample_data = data['Product_Description'][0]

In [ ]:
sample_data

'The Web Designer\x89Ûªs Guide to iOS (and Android) Apps, today @mention 10 a.m! {link} #sxsw'

##PREPROCESS DATA

In [ ]:
data = data.drop(['Text_ID','Product_Type' ], axis=1)
data

Product_Description  Sentiment
0     The Web Designer‰Ûªs Guide to iOS (and Android...          2
1     RT @mention Line for iPad 2 is longer today th...          2
2     Crazy that Apple is opening a temporary store ...          2
3     The lesson from Google One Pass: In this digit...          2
4     RT @mention At the panel: &quot;Your mom has a...          2
...                                                 ...        ...
6359  Thanks @mention for hosting this event #sxsw #...          2
6360  SXSW iPhone app is awesome, but iPad app crash...          1
6361  RT @mention RT @mention Download 20+ free trac...          2
6362  OH at Texas Social Media Awards: 'You don't ne...          2
6363  #Google launching a &quot;major&quot; new soci...          2

[6364 rows x 2 columns]

In [ ]:
def preprocess_data_lemmatize(text):
    cleaned_data = re.sub(r"[^A-Za-z\s]","", text )
    cleaned_data = cleaned_data.lower()
    cleaned_data = word_tokenize(cleaned_data)
    cleaned_data = [wnl.lemmatize(word) for word in cleaned_data if word not in stopwords.words('english')]
    cleaned_data =" ".join(cleaned_data)
    return cleaned_data

    

In [ ]:
def preprocess_data_stem(text):
    cleaned_data = re.sub(r"[^A-Za-z\s]","", text )
    cleaned_data = cleaned_data.lower()
    cleaned_data = word_tokenize(cleaned_data)
    cleaned_data = [ps.stem(word) for word in cleaned_data if word not in stopwords.words('english')]
    cleaned_data =" ".join(cleaned_data)
    return cleaned_data

    

In [ ]:
data['lemma_cleaned_text'] = data['Product_Description'].apply(preprocess_data_lemmatize)



In [ ]:
data['stem_cleaned_text'] = data['Product_Description'].apply(preprocess_data_stem)

In [ ]:
data

Product_Description  Sentiment  \
0     The Web Designer‰Ûªs Guide to iOS (and Android...          2   
1     RT @mention Line for iPad 2 is longer today th...          2   
2     Crazy that Apple is opening a temporary store ...          2   
3     The lesson from Google One Pass: In this digit...          2   
4     RT @mention At the panel: &quot;Your mom has a...          2   
...                                                 ...        ...   
6359  Thanks @mention for hosting this event #sxsw #...          2   
6360  SXSW iPhone app is awesome, but iPad app crash...          1   
6361  RT @mention RT @mention Download 20+ free trac...          2   
6362  OH at Texas Social Media Awards: 'You don't ne...          2   
6363  #Google launching a &quot;major&quot; new soci...          2   

                                     lemma_cleaned_text  \
0     web designer guide io android apps today menti...   
1     rt mention line ipad longer today yesterday sx...   
2     crazy apple opening temporary store austin tom...   
3     lesson google one pas digital environment user...   
4     rt mention panel quotyour mom ipad designing b...   
...                                                 ...   
6359  thanks mention hosting event sxsw sxswi iwanta...   
6360  sxsw iphone app awesome ipad app crash every t...   
6361  rt mention rt mention download free track ment...   
6362  oh texas social medium award dont need ask mot...   
6363  google launching quotmajorquot new social netw...   

                                      stem_cleaned_text  
0     web design guid io android app today mention l...  
1     rt mention line ipad longer today yesterday sx...  
2     crazi appl open temporari store austin tomorro...  
3     lesson googl one pass digit environ user want ...  
4     rt mention panel quotyour mom ipad design boom...  
...                                                 ...  
6359  thank mention host event sxsw sxswi iwantacr link  
6360  sxsw iphon app awesom ipad app crash everi tim...  
6361  rt mention rt mention download free track ment...  
6362  oh texa social media award dont need ask mothe...  
6363  googl launch quotmajorquot new social network ...  

[6364 rows x 4 columns]

##ENCODING

In [ ]:
from sklearn.model_selection import train_test_split


In [ ]:
labels = data["Sentiment"]
feature = data['lemma_cleaned_text']

In [ ]:
x_train, x_test, y_train, y_test  = train_test_split(feature,labels, test_size=0.3, random_state=142)

USING BAG OF WORDS

In [ ]:
x_train

5562    rt rumor apple opening temporary store downtow...
2281    developer learn mobile accessibility sxsw andr...
6212    google launch major new social network called ...
4082    barry diller say youre silly write content one...
5417    yeah wasnt got couldnt resist wearing blue jea...
                              ...                        
1616           mention awesome traded sxsw last year ipad
6317    spotted google map street view car wonder ill ...
5146    rt mention sxsw uxdes check designing ipad int...
4607               google handing free pi pi day sxsw win
277     shocked see google showcasing blogger sxsw tho...
Name: lemma_cleaned_text, Length: 4454, dtype: object

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(max_features=1000, ngram_range=(1,2))
feature_vec = vectorizer.fit_transform(x_train)

In [ ]:
print(vectorizer.get_feature_names_out())
print(feature_vec.toarray())

['aapl' 'aaron' 'aarpbulletin' ... 'zone' 'zuckerberg' 'zynga']


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


None


In [ ]:
feature_vec.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4454, 6707))